version: '3'
services:
    db:
        build: 
            context: ./db/
            dockerfile: DockerfileDB
        ports:
            - "5432:5432"
            #  api:
            #build:
            #context: ./api
            #dockerfile: DockerfileServer
